### ISSUE TITLE
Signale im Gleiswechselbetrieb

### ISSUE THREAD

**Issue by Kanaker** [sb12/OSMTrainRouteAnalysis#106]
Mir ist bei der Route der S 1 von Schöna nach Meißen aufgefallen, dass dort die Symbole für die Lage des Signals teilweise falsch sind. So stehen diese manchmal links vom Gleis, aber das Symbol zeigt als Lage rechts vom Gleis an.

**Comment by sb12** [comment]
Hallo,
bitte gib die OSM-id der Relation, bzw einen Link, sowie die node-id der betreffenden Signale an. Ansonsten ist es sehr schwierig den Fehler nachzuvollziehen.

**Comment by WolleDD** [comment]
Die ID lautet 3562518, das Signal ist unter anderem 1035585373.

**Comment by Kanaker** [comment]
U
