### ISSUE TITLE
Revision history is broken

### ISSUE THREAD

**Issue by bigbug21** [sb12/OSMTrainRouteAnalysis#115]
There are a few errors in the revision history ("Versionsgeschichte") section of the website:

*** cut ***
Warning: file(CHANGELOG.md) [function.file]: failed to open stream: No such file or directory in /users/osmtrainroutes/www/beta/functions/start.php on line 660

Warning: Invalid argument supplied for foreach() in /users/osmtrainroutes/www/beta/functions/start.php on line 662

Warning: Invalid argument supplied for foreach() in /users/osmtrainroutes/www/beta/functions/start.php on line 615
*** cut ***

**Comment by sb12** [comment]
Thanks for the notification.
There was a file missing in the beta version on the server. This should be fixed now.
