### ISSUE TITLE
Showing Sh 0 or Sh 2 of last buffer_stop

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#20]
In case a train ends on a buffer_stop, it would be nice to have the Sh 0 or Sh 2 from the buffer_stop in the list and a calculation of the length from the last distant signal to the buffer_stop signal.

**Comment by PeterDRS** [comment]
And the last main signal (if the route does not end on an Sh 0/Sh 2) of a route should be in Hp 0 state, the last distant signal should announce this.

**Comment by sb12** [comment]
The buffer stop and the last main signal showing hp0 should usually not be part of the route as the route ends at the last stop position and not at the last signal.
The H/V distant signal already shows vr0 when no corresponding main signal is found. I will add this for the ks distant / combined signal as well.

**Comment by PeterDRS** [comment]
That has nothing to do with reality!
A train route MUST end at a Hp 0 or Sh 0 or Sh 2 showing signal. It CANNOT end somewhere before.

I'm sorry but I have no understanding for such things that the route ends at the stop position. That's simply not the case and it would be a pitty to implement such an unrealistic behaviour. So please think about it.

**Comment by sb12** [comment]
Well, we are mapping public transport routes and not train routes.
Every train I have been in until now started at a stop position and ended at a stop position. Then it either turned around or it went to the depot (usually via the exit signal showing sh1), but I have never seen a train dropping of the passengers, then driving to the exit signal, stopping there, turning around and going back to the stop position to let passengers enter for the way back.

I think most public transport mappers think like this, so please discuss this in the forum or on the mailing list first.

**Comment by PeterDRS** [comment]
The stop position is often near to the buffer stop or last main signal.

Many OSM train routes I know go until such an element.

Please don't mix up the real position where the train stops with the controlled area until which a train may pass.

I hope your tool is also designed for people who are railway professionals. Or is your tool for so called "Fuzzies" that stand at the track and take photos?

In both cases you should please believe me that what I say is true. The route ends at the signal, not before. Please support rendering that last element, it's fundamental!

**Comment by sb12** [comment]
If the last signal is within the last 5 m of the route it will now show Hp 0.

I think this will suit both:
- "professional" routes that end at the signal
- "[OSM Wiki](http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Route)" routes that end ``with the way at the terminal stop position.``

**Comment by PeterDRS** [comment]
Why 5 meters?

If the route ends at a stop position the last signal is not passed. It is not an element of the route.

**Comment by sb12** [comment]
If the route ends at a stop position the last signal is the entry signal or an intermediate signal which should not show Hp0
