### ISSUE TITLE
Appearance of Ks signals

### ISSUE THREAD

**Issue by PeterDRS** [sb12/OSMTrainRouteAnalysis#22]
Ks signals should look like in reality:

* When repeated, the white light is only on in case of Ks 1 blinking or Ks 2
* Signals that are distant signals and are shortened have a light above. It is on in case of Ks 2, but only if the next main signal is in < {400,700,1000}*0,95 distance. It is not easy to determine this as it is not known what is the regular braking distance. But the signal should show a gray circle in the upper left corner
* In case of Zs 3 and Zs 3v showing the same speed the Zs 3v is off, Ks 1 is not blinking. There is only one big expection, if the Zs 3 is on an exit signal and the Zs 3v is for an upcoming block signal, where a little piece of "freie Strecke" is in between. Very, very seldom.

Mastschilder and Ne 2 would be interesting, too.

**Comment by sb12** [comment]
Thank you. I'm not so familiar with the ks system. I will have a look at that.

Another question about zs3 signals:
When the zs3 shows a higher speed than in the area before, is the zs3v turned on or off?
Example: http://osmtrainroutes.bplaced.net/beta/?id=5395605 signals 30W2t363 and 30Wt363

**Comment by PeterDRS** [comment]
That is correct. The distant signal MUST show the state of the following main signal. It MAY NOT show any other state.

The rule is just that the Zs 3v is suppressed when "announcing" something that is higher or same than the current speed, because that would be senseless (no need to deccelerate).

http://www.westfaelische-loksim-gesellschaft.de/signale/kssignal.html

**Comment by sb12** [comment]
So here the zs3v should be off for signals 30W2t363 and 30Wt363, right?

**Comment by PeterDRS** [comment]
Just think what I have written.

1. If the appearance was wrong, I would have opened an issue. But I didn't.
2. The distant signal MUST show the state of the main signal.
30W2t363 and 30Wt363 show Ks 1 blinking with Zs 3v "6". That is the announcement of the state of the main signal 30ZT363. So everything is right.

Just the main signal before does not show Zs 3v "6", it even has no Zs 3v. But if it had one, it would stay off.

**Comment by PeterDRS** [comment]
You closed this too early.

There are still problems:
* additional light for shortener
* Zs 3v ist off when Zs 3 is same or lower

**Comment by sb12** [comment]
> - additional light for shortener

should be solved by #31 

> Zs 3v ist off when Zs 3 is same or lower

Do you have an example where this does not work?

**Comment by PeterDRS** [comment]
> Do you have an example where this does not work?

Now it works.
