### ISSUE TITLE
Algorithm for Zs 3 calculation

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#24]
Could you describe in words how the algorithm for determining the Zs 3 speeds (or other ways of signalling speeds) works?

In this route 5372466 the signal 1722 has its Zs 3 off, in reality it shows 120.

How is the signalling system abstracted from the algorithm?

How is the interface? Would it be possible to implement real/fictional signal systems by just getting input data
* Main:
Pass/Halt/Substitute;
Speed
* Distant:
Announce pass/halt
Announce speed

which "outputs" a specific appearance. For example that the Hl system is implemented by just having a "module" called Hl renderer which makes the rendering, it just get's for example:
Pass with 60 km/h
and then makes the suitable graphics.

I think making the code more modular would be good. For that a well documented interface description is needed.

Together with that: For example a Ks should get: Pass 60 km/h main, pass 60 km/h distant and should know that the Zs 3v is not rendered. The rendering module of course has to get all the information about the signal from the specific OSM node.

**Comment by sb12** [comment]
> Could you describe in words how the algorithm for determining the Zs 3 speeds (or other ways of signalling speeds) works?

OK, I try:
- I have an array with all maxspeed zones, containing the maxspeed and the length of the maxspeed zone
- I then try to find the maxspeed which needs to be shown for each signal:
-  I have a loop through all maxspeed zones and for each maxspeed zone I check whether it is relevant.
- It is relevant, when either 
- the maxspeed zone starts before the signal and there is no new maxspeed up to 100 m after the signal, 
- the maxspeed zone starts less than 1000 m after the signal and less than 100 m before the signal.
- then the minimum of the relevant maxspeeds is saved for this signal

- I also try to find which distant, combined and main signals belong together based on the distance between them.

- Later when I show the signals in the table, I try to find the state of each signal based on the calculated maxspeed for this signal, or in case of a distant signal for the corresponding main signal.
- The graphic rendering then only gets the relevant tags of the signals and the state of the signals if known

> In this route 5372466 the signal 1722 has its Zs 3 off, in reality it shows 120.

Well the signal is at km 14.47 and the 120 km/h zone starts at km 15.53, so how should the tool know that this signal shows Zs3 120?

> I think making the code more modular would be good. For that a well documented interface description is needed.

I agree. The code is probably also not too easy to understand. Unfortunately I didn't have time yet to tidy up a little bit and think of some sort of concept to structure it better.

**Comment by PeterDRS** [comment]
> Well the signal is at km 14.47 and the 120 km/h zone starts at km 15.53, so how should the tool know that this signal shows Zs3 120?

I saw that the tool only seeks for the upcoming 1000 meters. That is definitely too less. At least 2000 meters should be seeked.

The 120 km/h is in the following switch point area, so it is evaluated by the signal box (of course in reality it is hard coded, not dynamically determined).

Also, the Lf7 "12" is not announced by an Lf6 "12", which in reality is only possible when the train comes with a same or higher speed out of a "following switch point area".

**Comment by sb12** [comment]
> I saw that the tool only seeks for the upcoming 1000 meters. That is definitely too less. At least 2000 meters should be seeked.

This should probably be changed to 
- search until the next main signal, but for not more than 2000 m

**Comment by PeterDRS** [comment]
Something to the modularization:

It just be consequently split the two aspects:
* caluclating speeds
* rendering signals

For this, there should be at least 2 files.

In the first file the Hp2, Zs3 or whatever should not appear.
In the second file everything regarding to the calculation should be removed.

So that - for example - I can write a "Hl-signal.php" without knowing anything about the calculation, or you can optimizing the calculation algorithm without knowing anything about the Hl system.

The second file should fetch the information from the node, not the calculation module.

**Comment by PeterDRS** [comment]
> search until the next main signal, but for not more than 2000 m

I implicted this fundamental thesis. ;)

**Comment by PeterDRS** [comment]
Perhaps you can search for a signal showing in opposite direction being an entry signal for stations or block signal for junctions. Then you are safe too that the point area is over.

Or we start to tag: railway:end_of_point_area=yes

which is also shown in "Buchfahrplan" with the Yen symbol.

**Comment by PeterDRS** [comment]
Why does in route 5421650 the signal 52ZU814 show Zs3 "4", although the following track allows 60 km/h?

**Comment by sb12** [comment]
It's the "1000m rule" again, it doesn't consider the position of the next main signal, yet.

**Comment by PeterDRS** [comment]
Interesting, that it only comes up seldom. I don't know any other example now.

**Comment by PeterDRS** [comment]
In http://osmtrainroutes.bplaced.net/beta/index.php?id=5455636&train=BR101IC the very last signals shows Zs 3 "4", although it should show Zs 3 "8" (or better show Hp 0).

**Comment by sb12** [comment]
> In http://osmtrainroutes.bplaced.net/beta/index.php?id=5455636&train=BR101IC the very last signals shows Zs 3 "4", although it should show Zs 3 "8" (or better show Hp 0).

This is fixed now.
