### ISSUE TITLE
Calculate route from local file

### ISSUE THREAD

**Issue by Nakaner** [sb12/OSMTrainRouteAnalysis#3]
There should be an option to calculate the route from an uploaded OSM-XML file. This would make users not to add fake stop positions in OSM relations of IC trains in order to have more stations displayed. ([example](http://osmtrainroutes.bplaced.net/?id=5372710&train=BR101IC) and [his motivation](http://www.drehscheibe-online.de/foren/read.php?3,7479333))

It may be a hidden feature and there may be difficulties. To make it easy, the provided OSM-XML should be formed like the Overpass query result, i.e. only as much data as necessary, no extra relations.

**Comment by sb12** [comment]
Thank you. This is a good idea e.g. to see how speed or signal changes affect the travel time.
I will have a look at this.

**Comment by sb12** [comment]
You can now upload any osm file that includes the relation and all needed ways and nodes, e.g. you can download a route in JOSM, edit it, save it and upload it to the tool.
It is also possible to share the link to the custom file by copying the URL of the page.
