### ISSUE TITLE
Warning - distance to next main

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#32]
Why does a distance to next main already throw a warning at 600 m?

That is an absolutely canonical value.

There are 3 values in Germany:
* 1000 m
* 700 m
* 400 m

These values can be shortened, if by more than 5%, an additional light is needed.

So the warning should start at 400*0,95=380 m

Perhaps it could be made dependent from the maxspeed.

There are maxspeeds for each braking distance. I don't know the exact values, but I think it's
0-60: 400m
61-120: 700m
121-160: 1000m

**Comment by sb12** [comment]
For Germany I found:
1000 m for main lines with maxspeed > 100 km/h
700 m for main lines with maxspeed <= 100 km/h
400 m for branch lines with maxspeed <= 80 km/h
and a tolerance of 95 - 150 %
Source: [Handbuch Eisenbahninfrastruktur, p.154](http://www.springer.com/us/book/9783642300202)

**Comment by PeterDRS** [comment]
That's not completely true.

400 m is also used on main lines, e.g. in Köln Hbf area.

There are lines for 120 km/h with 700 m. In this case the "Mindestbremshundertstel" are extremely high.

1000 m is neccessary for > 120 km/h, it CAN occurr on lower speeds.

On new lines the signals should be positioned at 1300 m.

For Hl signals, it is allowed to exceed the limit of 1500 m.

I would suggest to make the warning dependend from the signal if it has a shortened light or not.

**Comment by PeterDRS** [comment]
The maximum distant distance is 1500 m, but for Hl signals it is explicitely allowed to exceed this value for some meters.

1600 m is a good value to work with; the code is already changed. A warning should be thrown if the distance is higher than 1500 m and it is NOT a Hl signal.
