### ISSUE TITLE
Zs 3v does not show the proceeding Zs 3

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#33]
In route 5421650 the signal 52G shows Zs 3 "6", but the signal 5228, which is before, does not show Zs 3v "6", although it has a Zs 3v with capability for "6".

**Comment by sb12** [comment]
Mhm, for me signal 5228 does show the Zs 3v "6" and is blinking.

**Comment by PeterDRS** [comment]
Did you change something within the last minutes?

When I opened this issue it showed no Zs 3v.

Now, the signal 5228 shows Zs 3 "14".

Is it to ensure the shortened distance?

**Comment by sb12** [comment]
> Did you change something within the last minutes?
I only uploaded your pull request for the shortened distance, though I can't guarantee that it didn't include anything which I forgot to upload earlier.

> Now, the signal 5228 shows Zs 3 "14".

Is that wrong? It doesn't make much sense, because the maxspeed has been 140 km/h for over 50 km at that point, but this part of the tool does not "know" that. And are there situations where this could be correct?

**Comment by PeterDRS** [comment]
The maxspeed before is 160 km/h, at the signal 52G it is 150 km/h.

The Zs3 "14" is right for the situation where the signal shows Ks1 blinking with Zs 3v "6" to ensure that the train is as slow to brake to 60 km/h within the given distance.

If the signal shows Ks 2, it will show one of the lower Zs 3 speeds (90 km/h).

The Zs 3 "12" can be for Zs 3v "4".

**Comment by sb12** [comment]
It's just coincidence here, because the train maxspeed is 140.
I don't think it's possible to take these things into account as long as there is not a rule which applies at least for the majority of situations like these.

**Comment by PeterDRS** [comment]
There is a rule, but it is not public.

I try to find something that can be used.

Till then, the Zs 3 should stay off if there are no maxspeeds of the track. If the train maxspeed is lower than the track maxspeed, that should never be evaluated by the algorithm for Zs 3.

**Comment by PeterDRS** [comment]
![signale](https://cloud.githubusercontent.com/assets/13511519/9419583/2ec17d1a-485d-11e5-99f8-e21d530b2383.png)

Here one example in the route 63675

**Comment by PeterDRS** [comment]
In reality there are no Ks distant signals that can't show all the states of the following main signal.

In OSM data everything is possible. ;)

Though safety reasons make it possible that if a Ks distant signal can't show the correct state of the next main signal (e.g. it has no suitable Zs 3v) it MUST stay at Ks 2. That is the safest state. As I said, in reality it's not possible but the tool should not support such senseless states. ;)

**Comment by sb12** [comment]
The main problem of this issue has been solved.
