### ISSUE TITLE
Gaps in route?

### ISSUE THREAD

**Issue by PeterDRS** [sb12/OSMTrainRouteAnalysis#34]
Why does 3599907 shall have 2 gaps in route?

I suggest - beside this - to add the link to the route analyzer to every route, not only the ones with gaps.

**Comment by sb12** [comment]
> Why does 3599907 shall have 2 gaps in route?

Load it in JOSM (use the link on the bottom of the page) and [you can find them](http://www.openstreetmap.org/relation/3599907#map=18/51.07342/13.75085). No idea why the route analyzer can't find it.

> I suggest - beside this - to add the link to the route analyzer to every route, not only the ones with gaps

This can be done in #12.

**Comment by PeterDRS** [comment]
Ah I see. It is not a "gap", it just is a piece of track which is not used by the train.
