### ISSUE TITLE
Zs 3 light with only one state

### ISSUE THREAD

**Issue by PeterDRS** [sb12/OSMTrainRouteAnalysis#39]
There are Zs 3 signals that are light form but only have one state.

They are not shown, as the "explode" function fails.

Example: Route 63675, Signal node id 2608573933

**Comment by sb12** [comment]
Works for me (didn't change the code since Thursday, maybe a caching issue?):
![zs3](https://cloud.githubusercontent.com/assets/5783139/9423278/027b6c14-48be-11e5-8fb3-609a2f1be015.png)

The explode function shouldn't fail if there's only one value, in this case it returns this value.

**Comment by PeterDRS** [comment]
For me not.
![signale2](https://cloud.githubusercontent.com/assets/13511519/9423334/02191f9e-48c0-11e5-9b77-56e452fdd686.png)

**Comment by sb12** [comment]
Strange. Could you send me the link to the signal image, please.

**Comment by PeterDRS** [comment]
<object type="image/svg+xml" data="img/signals/signal.php?railway%3Asignal%3Acombined=DE-ESO%3Aks&railway%3Asignal%3Acombined%3Aform=light&railway%3Asignal%3Acombined%3Astates=DE-ESO%3Ahp0%3BDE-ESO%3Aks1%3BDE-ESO%3Aks2&railway%3Asignal%3Acombined%3Asubstitute_signal=DE-ESO%3Adb%3Azs7&railway%3Asignal%3Aspeed_limit=DE-ESO%3Azs3&railway%3Asignal%3Aspeed_limit%3Aform=light&railway%3Asignal%3Aspeed_limit%3Aspeed=60&&speed=&state_combined=ks1" class="svg signal">

**Comment by sb12** [comment]
Can't find any bug here. Could you check if the data is up to date (shown on the bottom of the page) and send me an image of the speed profile?

**Comment by PeterDRS** [comment]
Link: http://osmtrainroutes.bplaced.net/beta/?id=63675&train=BR442.3

I noticed that there are two "&".
![speed](https://cloud.githubusercontent.com/assets/13511519/9423491/59be9cf0-48c6-11e5-9266-9762bd147e3b.png)

**Comment by sb12** [comment]
Ok, should work now. Problem was a bug in the speed calculation.
I didn't see it, because I used a different train with a different speed profile.

**Comment by PeterDRS** [comment]
The train should not influence the signal, cf #42
