### ISSUE TITLE
Kennlicht for signals which will be deactivated

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#45]
To support a function to only use one signal of a group of two a relation must be created.

The tool must detect that the signal is in this excluding relation and only activate one of the two signals (can be the first one) and deactivate the other one (showing Kennlicht/marker light).

**Comment by sb12** [comment]
This should work already:

[![kennlicht](https://cloud.githubusercontent.com/assets/5783139/9423254/d2c190d0-48bc-11e5-8a50-00ccd8527cb2.png)](http://osmtrainroutes.bplaced.net/beta/?id=1483886&train=BR425)

If you know a situation where it doesn't work, please send a link to the route and the signal.

**Comment by PeterDRS** [comment]
In route 3562518 the signal ZS705 shows Kennlicht in reality. The signal ZS704 shows Zs 3 "6".

**Comment by sb12** [comment]
> The signal ZS704 shows Zs 3 "6".

This has been solved. Problem was that the 100 m after the signal hasn't been evaluated, this distance has been reduced to 20 m. Reason for this is that the maxspeed change is not always mapped directly at the signal, but sometimes a few meters before or after.

>In route 3562518 the signal ZS705 shows Kennlicht in reality.

Yes that doesn't work, yet. The code for the Kennlicht still needs to be improved.
