### ISSUE TITLE
Show all main aspect signals

### ISSUE THREAD

**Issue by PeterDRS** [sb12/OSMTrainRouteAnalysis#6]
It would be nice to have a list - on a seperate page - for all passed main aspect signals (railway:signal:main) on the nodes of the route (in the direction of the train).

That would be a beginning for calculating speeds of "Fahrstraßen" to improve the travelling time calculation.

**Comment by Nakaner** [comment]
@sb12: Please note that signals which can show main and distant signal aspects are tagged as `railway:signal:combined=*`. This affects Ks, Hl ans Sv signals in Germany.

**Comment by PeterDRS** [comment]
It's about to change, so no need to do it complicated.

**Comment by Nakaner** [comment]
@PeterDRS wrote:
> It's about to change, so no need to do it complicated.

May I have a look into your crystal ball? I also need some information about the future.

**Comment by PeterDRS** [comment]
No, you may not.

**Comment by sb12** [comment]
Thanks for the proposal, Peter.
I'm currently working on showing main, distant, combined and speed signals for a route. 
In the future this can then be used to calculate speeds also based on signals and not only based on the way speed limits, e.g. for diverging routes.

**Comment by PeterDRS** [comment]
Can you show a first version or have you not yet written any code for this?

**Comment by sb12** [comment]
First version as a list:
![signals1](https://cloud.githubusercontent.com/assets/5783139/9151150/0c1f587c-3df9-11e5-87a8-50f8c3e84097.png)
![signals2](https://cloud.githubusercontent.com/assets/5783139/9151151/0c243f04-3df9-11e5-8853-507197af4461.png)

This already tries to guess the shown signal state based on the maxspeed, which actually works quite ok in well mapped regions (This is the RB2 route from Karlsruhe to Mannheim).

Currently German H/V light, Ks, zs3 and zs3v signals are supported (partly based on @Nakaner's icons). I will probably have a fallback solution for other signals (based on railway:signal:main/distant/combined and railway:signal:form=light/semaphore) for now but may include them later.

The svg images are currently produced on the fly (including the ref) which has some performance issues on long distance routes, so I need to rethink that.

It also still has a few bugs.
If you have any suggestions how to improve the list, I'm happy to hear about it.
@bigbug21 might also be interested.

**Comment by PeterDRS** [comment]
Is it public? I mean can you give me a link or is it hosted locally?

It is ok that there are icons and it is graphic oriented. I myself am more interested in pure data and numbers (calculations), so don't mind when I am not so interested in the graphics.

Can you show me the code somewhere?

**Comment by PeterDRS** [comment]
I have some suggestions for now:
- show the type of signal (entry, exit, block, ...)
- show the exact position of the signal refering to the track (using the milestones and then measuring the rest piece)
- show the time when the signal is passed
- show stop positions when they are passed in between

**Comment by sb12** [comment]
> Is it public? I mean can you give me a link or is it hosted locally?

Sorry it's only on a local server and I haven't merged the code, yet, since it still needs some work/tidy up.

I will have a look at your suggestions and see if I can implement them.

**Comment by PeterDRS** [comment]
I don't know why you don't upload it to github and put it on a public server.

I can read PHP code.

Are you frightened I could see something that is wrong?

For me it is important to test if my taggings are correct/work well.

**Comment by sb12** [comment]
I'm doing this in my free time and so it should be completely up to me which code I want to upload to github and whether I want to provide a public server.

For me it is much easier to work on my private local server. I could have a beta version running on the public server at some point, but for now this is not planned.

I also only upload code to github that is actually working and not some experimental versions with dirty hacks and potential security issues.

**Comment by PeterDRS** [comment]
Ok, I'm sorry, you do it in your extra time.

I'm a business man and want to sale your product. The money goes to me, you get nothing. Do you agree? ;)

**Comment by rurseekatze** [comment]
Nice! Looks very good even in this experimental state.

A question to the column 'position': If the signals stands on the left side of the track in combination with Ne 4 sign, does the application use a icon showing the signal on the left side and a Ne 4 sign on the right side? That would be pretty cool...

Another question: If there are multiple values for Zs 3(v), which one is shown in the list?

> * show the type of signal (entry, exit, block, ...)

Is this necessary in Germany? It should be distinguishable with the icon and the signal ref.

> * show the exact position of the signal refering to the track (using the milestones and then measuring the rest piece)
> * show the time when the signal is passed

+1

**Comment by PeterDRS** [comment]
The signal type is absolutely not recognizable from the signal.

Please believe me I am a railway expert. ;)

It will get important for knowing when the "Anschließender Weichenbereich" is over. For that purpose you would need to look for an Esig of the opposite direction. Or we have to tag the end of points area.

**Comment by sb12** [comment]
> A question to the column 'position': If the signals stands on the left side of the track in combination with Ne 4 sign, does the application use a icon showing the signal on the left side and a Ne 4 sign on the right side? That would be pretty cool...

It does, but all the Ne4 signs I know are positioned in the "Gegengleis" so they never show up in the analysis. If you know of a Ne4 sign in the "Regelgleis" please let me know, so that I can test whether it actually works. 
It will also show a bridge when the signal is mounted on a signal bridge.

> Is this necessary in Germany? It should be distinguishable with the icon and the signal ref.

Well for a railway signal expert it should, but we still don't know whether it is correctly marked as entry signal in the data.

**Comment by PeterDRS** [comment]
In Dresden main station is a signal Ne 4 in a "Bahnhofsgleis". What is that? Is that a "Regelgleis"?

The signal stands on the left and the Ne 4 on the right.

The meaning of a signal is fundamental, not only for signal experts, but also for train drivers and to calculate the point where the acceleration on track line speed is allowed.

If the data is correct or not is another problem. It is not a problem of a tool, of a renderer. It is even good if a tool shows it so that a human being can recognize the error and fix it. For that (and for orientation) it would be good to see the name of the stations, even if there are no stops.

In advance, there could be departure times in form of "Durchfahrzeiten" which are measured at special points (middle of station building if one exists). I am about to propose to mark this point as a node in the way (virtual stop position).

**Comment by PeterDRS** [comment]
Here is the node of the signal that stands left with an Ne 4 right: ID 2375515458

**Comment by sb12** [comment]
I now commited a first version of the signal table. A beta version is available at http://osmtrainroutes.bplaced.net/beta

I now also added a description of the signal including the function (entry, exit etc.) and the possible speed limit values.

> Another question: If there are multiple values for Zs 3(v), which one is shown in the list?

The value of the speed signals are guessed by evaluating the maxspeed in the section behind the signal. This works quite well already for most cases.

>Here is the node of the signal that stands left with an Ne 4 right: ID 2375515458

See http://osmtrainroutes.bplaced.net/beta/index.php?id=3599907&train=regional at km 17.25

**Comment by sb12** [comment]
> show the exact position of the signal refering to the track (using the milestones and then measuring the rest piece)

I opened a new issue #19, as this is also interesting for the maxspeed graph.

**Comment by PeterDRS** [comment]
Nice, nice.

The captions are quite wide at Ks system.

So it is neccessary to force a proposal to use ref:area_code and then either don't show the area code or put in a new line.

**Comment by PeterDRS** [comment]
> The value of the speed signals are guessed by evaluating the maxspeed in the section behind the
> signal. This works quite well already for most cases.

It does not work, if the allowed speed after the signal is higher, for example in this route: 5395605

Zs 3: 50, 40

Following track speed limits: 50, 60

So in this case the 50 should be selected!

**Comment by PeterDRS** [comment]
This route is also a good example why it should be made possible to mark a combined signal as showing no distant state: Signal 19H in Radebeul Ost shows no distant state, the tool shows "?".

If the scheme was with railway:signal:distant:states it would be easy to add "off".

With the current scheme it is not so easy.

**Comment by sb12** [comment]
> The captions are quite wide at Ks system

How are they shown in reality? Are they written in one line?
In my regions many signals have refs like
```
38
123
```
in two lines, but there's no possibility to enter line breaks, yet, and I'm also not sure if this would be a good idea.

> It does not work, if the allowed speed after the signal is higher

This is fixed now.

**Comment by PeterDRS** [comment]
The caption in reality is not always the same.

In theory, the first line has the area code, the second line the name of the object, e.g.

62
P4

or
5
23

Sometimes in old amenities it is for example "5P4".

I even saw 3 lines when there is no space:
33
ZS5
25

I think two lines would be great.

**Comment by bigbug21** [comment]
What a nice first shot at this!! Although it is still in beta stage, there are some real nice features. It would be good to also include the LZB and ETCS equivalents of main signals in the signals tabs, at least as a checkbox option. (tags: railway:signal:train_protection=DE-ESO:blockkennzeichen and railway:signal:train_protection=DE-ESO:ne14).

For trail runs: There are a number of those (LZB) "main signal boards" between Riesa and Leipzig at http://osmtrainroutes.bplaced.net/beta/?id=60685&train=ICE-T7#signalsTab

**Comment by bigbug21** [comment]
Changes of direction should be included in the list and, at least as distances are concerned, be treated like a main signal.

Example: http://osmtrainroutes.bplaced.net/beta/?id=60685&train=ICE-T7&rf=1 at km 118.97 (last (?) main signal before the stop in Leipzig Central) and km 495.95 (the last main signal before changing direction in Frankfurt main station).

**Comment by PeterDRS** [comment]
I think it's a better idea to support direction changes only by splitting the route in segments.

Otherwise the tool cannot know how where the train turns.

**Comment by sb12** [comment]
> It would be good to also include the LZB and ETCS equivalents of main signals in the signals tabs

Yes, already thought about them.

> Changes of direction should be included in the list and, at least as distances are concerned, be treated like a main signal.

True these should be shown.

> Otherwise the tool cannot know where the train turns.

Should be easy: whenever a route goes through the same way twice in a row it probably turned around or there's a error in the route.

**Comment by emiriku** [comment]
Adding the passed stations to the list of signals would improve orientation within the list a lot. This could be possible by evaluating the public_transport = stop_position nodes?

**Comment by PeterDRS** [comment]
In case of main tracks without platforms a new tagging is needed: measuring_points ("Fahrzeitmesspunkt").
