### ISSUE TITLE
findState should do a check/validation

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#64]
If I understood it correct the findState sends a speed to the signal and gets the appropriate state.

That should be absolutely fail safe, meaning the signal MUST check if the Zs 3v or Hl or Vr states do exist. Additionally it is intentional that some Vr signals have not Zs 3v but a Zs 3 "6" follows. In this case it shows Vr2 without a Zs 3v.

Or the Hl signals should show the lowest state they can. If they cannot show an appropriat state, the signal MUST stay at the warning state. A warning can be thrown.

BTW: That is the real behaviour if something is broken. E.g. a Zs 3v is defect, the signal CAN'T go to the desired state. It would be nice to emulate this here too.

Showing Ks 1 without a Zs 3v and a Zs 3 follows is absolutely dangerous.

Of course I know the data is wrong, but that is something that can always occur.

**Comment by PeterDRS** [comment]
Cf. #74

**Comment by sb12** [comment]
This has been implemented, though it might need some more testing and doesn't cover all special cases, yet.
