### ISSUE TITLE
Debugging purposes: Show next_speed, next_speed_distant

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#70]
The whole systen is quite buggy now, so I would like to see the next_speed, the next_speed_distant and the states of the signals that findState returned.

Then it is possible to look if all the algorithms work or not and where the problem is.

In a second step the algorithms have to be made fail safe, meaning that findState always sticks to the safe side if something is wrong (e.g. stay in Ks2 when no Zs 3v is available).

**Comment by sb12** [comment]
This is shown now.
