### ISSUE TITLE
Classes model for signals

### ISSUE THREAD

**Issue by ghost** [sb12/OSMTrainRouteAnalysis#75]
To make it easier do so some checks with the signals the classes should be hierarchical.

That means:
base class for:
* signal
 - main signal
   - Zs3 (or virtual speed class for Hl/HV)
 - distant signal
   - Zs3v (or virtual speed class for Hl/HV)

From the distant signal class there shall be access to the Zs3v to do checks.

**Comment by PeterDRS** [comment]
Before you write code I would prefer to discuss the scheme first.

It would additionally be senseful to put the maxspeed array to the start signal that allows the drive.

Therefore this array must be split in pieces where Zs3 standalone signals stand.
