### ISSUE TITLE
Color of green

### ISSUE THREAD

**Issue by PeterDRS** [sb12/OSMTrainRouteAnalysis#79]
It is not a good idea to harcode the green colour as "&green;".

I had changed the code to use $green, unfortunately it was undone.

The real used green at DB is not &green; but something like "#38fff5" or &cyan;

**Comment by sb12** [comment]
> It is not a good idea to harcode the green colour as "&green;".

???

> I had changed the code to use $green

It's easier to define the colours directly in the svg than carrying around multiple php variables through all signal classes.

>unfortunately it was undone.

It wasn't undone, it was improved. Nobody's code is perfect ;)

>The real used green at DB is not &green; but something like "#38fff5" or &cyan;

Currently #00ff00 is used, "green" would be #008000. There's no defined DB signal green as it all differs based on the light source (gas light, led, light bulb), the glass colour and the monitor brightness/saturation etc., but if you find a better green, you are welcome to provide a pull request.
When I created the signals it wasn't important for me whether their appearance is exactly like the original, I was more interested on their function, so I just chose the basic colours light green, red and yellow

**Comment by PeterDRS** [comment]
No, it is not #00ff00, it is &green;. Or am I blind?

> There's no defined DB signal green

That's completely wrong. Of course there is a definition and every manufacturer of signals has to make sure to meet the requirements. Don't ask me for the RGB value but &cyan; or #38fff5 is nice.

Can you change the code to use a variable $green so I just have to adjust this variable? ;)

**Comment by sb12** [comment]
[Adjust me!](https://github.com/sb12/OSMTrainRouteAnalysis/blob/master/img/signals/signal.php#L256)

**Comment by PeterDRS** [comment]
I have nearly no experiency with SVG. It would be good if you could explain your design, where you code what. So it is hard to get the overview... so many different files. And not intuitive. ;)

**Comment by sb12** [comment]
The ENTITIES are just like constants. The colour entities define the colours you used, so instead of 
`fill = "'.$green.'"` you can now write `style="&green;"`.
The st0,st1,st2 etc. are used for the matrix signals.
The signal.php only includes the basic svg code and calls the functions for the different signals.

There's one class for each signal type. Every signal class has a function to calculate the state based on speed limits etc., a function to show a signal description and a function to write the svg code for the image. Sometimes there are classes in between to reduce redundancy (e.g. the signal_matrix.php).

**Comment by PeterDRS** [comment]
Now I know this all, but it took time. I looked at the code.

Still the problem: Calculation and presentation is not split up: In getData.php there is fetching data, calculating things an presenting them in one big file.

Would think to split it:
* fetch data from database and fill internal structures (objects)
* doing calculation things
* showing things to user

BTW: Would be a nice feature to make a signal clickable where a new page opens showing the signal in the state of the route, but allowing to do state changes. Very nice, too, would be a comparison: How would the state of this signal look in the other signal systems? (That also allows people to look at a signal e.g. Hl, which they don't understand, and "translate" it to Ks or H/V, which is then understandable). Just as a (easy to implement) gimmick.

**Comment by sb12** [comment]
> Still the problem: Calculation and presentation is not split up: In getData.php there is fetching data, calculating things an presenting them in one big file.

Yes, the getData.php is a big mess, mixing up a lot of things. This definitely needs to be separated into different files. Anyway this should discussed in a new issue as it has nothing to do with the color of green.

> BTW: Would be a nice feature to make a signal clickable where a new page opens showing the signal in the state of the route, but allowing to do state changes. Very nice, too, would be a comparison: How would the state of this signal look in the other signal systems? (That also allows people to look at a signal e.g. Hl, which they don't understand, and "translate" it to Ks or H/V, which is then understandable). Just as a (easy to implement) gimmick.

Could you open a new issue for this, please.

**Comment by PeterDRS** [comment]
> Could you open a new issue for this, please.

Obama: Yes, I can.

I just doubt I open hundreds of thounsands of issues here... ;)
